from tkinter import *
def press(numbers):
    global operator
    operator = operator + str(numbers)
    textinput.set(operator)
def buttclear():
    global operator
    operator = ""
    textinput.set("")
def buttequal():
    global operator
    Sum=str(eval(operator))
    textinput.set(Sum)
    operator = ""
a=Tk()
a.geometry("500x400")
a.title("Calculator")
operator = ""
textinput=StringVar()
ent=Entry(a,bg='lightblue',fg='black',font="Century 20 bold",bd=10,width=29,textvariable=textinput)
ent.place(x=0,y=0)
butt1=Button(a,text='1',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(1))
butt1.place(x=0,y=55)
butt2=Button(a,text='2',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(2))
butt2.place(x=120,y=55)
butt3=Button(a,text='3',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(3))
butt3.place(x=240,y=55)
butt4=Button(a,text='4',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(4))
butt4.place(x=0,y=120)
butt5=Button(a,text='5',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(5))
butt5.place(x=120,y=120)
butt6=Button(a,text='6',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(6))
butt6.place(x=240,y=120)
butt7=Button(a,text='7',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(7))
butt7.place(x=0,y=185)
butt8=Button(a,text='8',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(8))
butt8.place(x=120,y=185)
butt9=Button(a,text='9',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(9))
butt9.place(x=240,y=185)
butt0=Button(a,text='0',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press(0))
butt0.place(x=0,y=250)
buttclear=Button(a,text='Clear',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = buttclear)
buttclear.place(x=120,y=250)
butteq=Button(a,text='=',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = buttequal)
butteq.place(x=240,y=250)
buttdiv=Button(a,text="/",font="Century 20 bold",fg='lightblue',bg='black',height=1,width=6,bd=6,command = lambda:press("/"))
buttdiv.place(x=360,y=55)
buttmul=Button(a,text="*",font="Century 20 bold",fg='lightblue',bg='black',height=1,width=6,bd=6,command = lambda:press("*"))
buttmul.place(x=360,y=120)
buttmn=Button(a,text="-",font='Century 20 bold',fg='lightblue',bg='black',height=1,width=6,bd=6,command = lambda:press("-"))
buttmn.place(x=360,y=185)
buttpl=Button(a,text='+',font="Century 20 bold",fg='lightblue',bg='black',height=1,width=6,bd=6,command = lambda:press("+"))
buttpl.place(x=360,y=250)
buttd=Button(a,text='.',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda: press("."))
buttd.place(x=0,y=315)
buttp=Button(a,text='%',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press("%"))
buttp.place(x=120,y=315)
buttsq=Button(a,text='**',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press("**"))
buttsq.place(x=240,y=315)
buttfac=Button(a,text='!',fg='lightblue',bg='black',font='Century 20 bold',height=1,width=6,bd=6,command = lambda:press("!"))
buttfac.place(x=360,y=315)
a.mainloop()
